name = "bpm-rule-api"
main = "src/worker.ts"
compatibility_date = "2025-10-25"

[vars]
ENV = "dev"

[[kv_namespaces]]
binding = "RULES_CACHE"
id = "kv_namespace_id_placeholder"

[[kv_namespaces]]
binding = "API_CACHE"
id = "bpm-cache"

[[d1_databases]]
binding = "DB"
database_name = "bpm_rule_db"
database_id = "d60a51ef-7b78-4eee-b816-828f05b958df"

[[services]]
binding = "BPM_API"
service = "bpm-rule-api"
